name: Build macOS dylib

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        xcode-select --install || true
        brew install gcc || true
        
    - name: Build dylib
      run: |
        gcc -shared -fPIC reset_keys.c -o libreset.dylib
        
    - name: Verify output
      run: file libreset.dylib
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 使用 v4 版本
      with:
        name: dylib-output
        path: libreset.dylib
