name: Build Non-Jailbroken iOS dylib

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install iOS dependencies
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept
        brew install ldid
        
    - name: Build dylib
      run: |
        SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
        
        # 编译为位置无关的动态库
        clang -arch arm64 \
              -isysroot $SDK_PATH \
              -framework Foundation \
              -framework UIKit \
              -dynamiclib \
              -fobjc-arc \
              -fPIC \
              -o libInputFix.dylib \
              inputfix.c
        
        # 为动态库签名（使用临时证书）
        ldid -S libInputFix.dylib
        
        # 验证文件
        file libInputFix.dylib
        otool -L libInputFix.dylib
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: non-jb-dylib-output
        path: libInputFix.dylib
