name: Build iOS Input Fix dylib

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install iOS dependencies
      run: |
        # 安装iOS开发工具链
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept
        brew install ldid # 用于iOS签名
    
    - name: Build dylib for iOS
      run: |
        # 设置iOS SDK路径
        SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
        
        # 编译为iOS动态库 (arm64架构)
        clang -arch arm64 \
              -isysroot $SDK_PATH \
              -framework Foundation \
              -dynamiclib \
              -fPIC \
              -F . \
              -o libInputFix.dylib \
              inputfix.c
        
        # 为iOS设备签名 (使用临时证书)
        ldid -S libInputFix.dylib
        
        # 验证文件
        file libInputFix.dylib
        otool -hv libInputFix.dylib
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-dylib-output
        path: libInputFix.dylib
